christiangh_main_cgh_website_homepage:
    locales:  { es: "/", en: "/en/" }
    defaults: { _controller: ChristianghMainCghWebsiteBundle:Default:homepage }

christiangh_main_cgh_website_contact:
    locales:  { es: "/es/contacto.html", en: "/en/contact.html" }
    defaults: { _controller: ChristianghMainCghWebsiteBundle:Default:contact }

christiangh_main_cgh_website_my_cv:
    locales:  { es: "/es/mi-curriculum-vitae.html", en: "/en/my-curriculum-vitae.html" }
    defaults: { _controller: ChristianghMainCghWebsiteBundle:Default:myCV}

christiangh_main_cgh_website_web_map:
    locales:  { es: "/es/mapa-web.html", en: "/en/web-map.html" }
    defaults: { _controller: ChristianghMainCghWebsiteBundle:Default:webMap }